#!/bin/bash

PIDFILE=tmp/pids/thin.pid
RAILS_ENV=production

rvm_env="/usr/local/rvm/scripts/rvm"

if [[ -s $rvm_env ]]; then
  source $rvm_env  # This loads RVM into a shell session.
else
  printf "ERROR: An RVM installation was not found.\n" && exit 1
fi

# use ruby specified in project .rvmrc
export rvm_project_rvmrc=1
export rvm_trust_rvmrcs_flag=1
export rvm_ignore_rvmrc=0

action='start'

if [ -e "$PIDFILE" ]; then
  action='restart'
fi

thin="./bin/thin --daemonize --pid $PIDFILE --environment $RAILS_ENV $action"
$thin
