#!/bin/bash

PIDFILE=tmp/pids/thin.pid
RAILS_ENV=production

action='start'

if [ -e "$PIDFILE" ]; then
  action='restart'
fi

thin="./bin/thin --daemonize --pid $PIDFILE --environment $RAILS_ENV $action"
$thin
